CREATE TABLE MENSAJES (
    MENSAJE VARCHAR2(100),
    FECHA DATE
);

CREATE OR REPLACE TRIGGER tr_ARTICULOS_Ins
BEFORE INSERT 
ON ARTICULOS
FOR EACH ROW
BEGIN
    INSERT INTO MENSAJES VALUES ('Alguien ha insertado un registro', SYSDATE);
END;

INSERT INTO ARTICULOS VALUES ('SE98', 'SE', 'SEILLA', 250, 12, 1, 25);
SELECT * FROM ARTICULOS;
SELECT * FROM MENSAJES;

CREATE TABLE ART2 AS
    SELECT * FROM ARTICULOS;
    
SELECT * FROM ART2;

INSERT INTO ARTICULOS 
    SELECT * FROM ART2;

CREATE OR REPLACE TRIGGER tr_ARTICULOS_Ins3
BEFORE INSERT 
ON ARTICULOS
FOR EACH ROW
BEGIN
    INSERT INTO MENSAJES VALUES (USER || ' Ha insertado un registro con codigo' || :NEW.CCODART, SYSDATE);
END;

-- TRIGGER PARA EL UPDATE

CREATE OR REPLACE TRIGGER tr_ARTICULOS_Up4
BEFORE UPDATE 
ON ARTICULOS
FOR EACH ROW
BEGIN
    INSERT INTO MENSAJES VALUES (USER || ' Ha actualizado el registro' || :NEW.CCODART, SYSDATE);
END;

-- TRIGGER PARA EL DELETE

CREATE OR REPLACE TRIGGER tr_ARTICULOS_De5
BEFORE DELETE
ON ARTICULOS
FOR EACH ROW
BEGIN
    INSERT INTO MENSAJES VALUES (USER || ' Ha borrado el registro' || :OLD.CCODART, SYSDATE);
END;


